// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfvsP500uUI-fS9_YqDVcHOZeX3ZcO1-g',
    appId: '1:201595636610:web:fe4a01d1642e2c3a981d9b',
    messagingSenderId: '201595636610',
    projectId: 'zartek-d160c',
    authDomain: 'zartek-d160c.firebaseapp.com',
    storageBucket: 'zartek-d160c.firebasestorage.app',
    measurementId: 'G-3J9LNWS5FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSEbH95gyezwwgtMjsTKeWlULzNzd2dig',
    appId: '1:201595636610:android:9929cfe4f6211995981d9b',
    messagingSenderId: '201595636610',
    projectId: 'zartek-d160c',
    storageBucket: 'zartek-d160c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPa508ODq6PoLAWvYrVzSPiIqO3YFPU6w',
    appId: '1:201595636610:ios:007567f3f6cab61b981d9b',
    messagingSenderId: '201595636610',
    projectId: 'zartek-d160c',
    storageBucket: 'zartek-d160c.firebasestorage.app',
    iosBundleId: 'com.example.zartek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPa508ODq6PoLAWvYrVzSPiIqO3YFPU6w',
    appId: '1:201595636610:ios:007567f3f6cab61b981d9b',
    messagingSenderId: '201595636610',
    projectId: 'zartek-d160c',
    storageBucket: 'zartek-d160c.firebasestorage.app',
    iosBundleId: 'com.example.zartek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfvsP500uUI-fS9_YqDVcHOZeX3ZcO1-g',
    appId: '1:201595636610:web:a0164a5459336b6e981d9b',
    messagingSenderId: '201595636610',
    projectId: 'zartek-d160c',
    authDomain: 'zartek-d160c.firebaseapp.com',
    storageBucket: 'zartek-d160c.firebasestorage.app',
    measurementId: 'G-7QT59QLKBX',
  );

}